### ISSUE TITLE
White background shows up on certain displays

### ISSUE THREAD

**Issue by chao-xian** [alphagov/dsp-dashboard#18]
I think I broke the html+css on this... need help

![Screenshot 2024-09-05 at 09 59 09](https://github.com/user-attachments/assets/ff6b8443-7f2f-40df-9b41-fa4c6814e06e)
![dsp-dashboard-38e19dd42f71 herokuapp com_(iPhone SE)](https://github.com/user-attachments/assets/880f5e91-b7be-47e4-b5d5-a49c8dbbe6fd)

**Comment by DavidBiddle** [comment]
Fixed in #25 by @thomasiles 🥇
